# Chapter 4: pandas Series and DataFrames

Companion notebook for *Master Data Cleaning: A Hands-On Beginner's Guide with Python, pandas & NumPy*.

Run the cells from top to bottom (**Kernel → Restart Kernel and Run All Cells**). The data files this chapter uses are in the same folder as this notebook.

## 4.1 The pandas Series

### `pd.Series()`

In [1]:
import numpy as np
import pandas as pd

temps_list = [88.7, 91.4, 85.6, 90.3]
temps_default = pd.Series(temps_list)
temps_default

0    88.7
1    91.4
2    85.6
3    90.3
dtype: float64

In [2]:
cities = ['New York', 'Philadelphia', 'Denver', 'Los Angeles']
temps = pd.Series(temps_list, index=cities)
temps

New York        88.7
Philadelphia    91.4
Denver          85.6
Los Angeles     90.3
dtype: float64

In [3]:
quarterly_sales = pd.Series(
    {'Q1': 15000, 'Q2': 18500, 'Q3': 21000, 'Q4': 23500}
)
quarterly_sales

Q1    15000
Q2    18500
Q3    21000
Q4    23500
dtype: int64

### Accessing values by label and by position

In [4]:
print(temps['Denver'])
print(temps.iloc[2])

85.6
85.6

### Slicing

In [5]:
temps['Philadelphia':'Los Angeles']

Philadelphia    91.4
Denver          85.6
Los Angeles     90.3
dtype: float64

In [6]:
temps.iloc[1:3]

Philadelphia    91.4
Denver          85.6
dtype: float64

In [7]:
temps.head(2)

New York        88.7
Philadelphia    91.4
dtype: float64

### `s.describe()`

In [8]:
prices = pd.Series([29.99, 45.50, 19.99, 89.00,
                    34.99, 23.50, 67.00, 12.99])
prices.describe()

count     8.000000
mean     40.370000
std      25.875099
min      12.990000
25%      22.622500
50%      32.490000
75%      50.875000
max      89.000000
dtype: float64

In [9]:
print(prices.sum())
print(prices.median())
print(prices.max())

322.96
32.49
89.0

### `s.isna()`

In [10]:
daily_sales = pd.Series(
    [250, 300, None, 275, 310, None, 290],
    index=['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
)
daily_sales.isna()

Mon    False
Tue    False
Wed     True
Thu    False
Fri    False
Sat     True
Sun    False
dtype: bool

In [11]:
daily_sales.isna().sum()

np.int64(2)

### `s.value_counts()`

In [12]:
ratings = pd.Series(['Excellent', 'Good', 'Average', 'Good',
                     'Excellent', 'Good', 'Poor', 'Excellent',
                     'Average', 'Good'])
ratings.value_counts()

Good         4
Excellent    3
Average      2
Poor         1
Name: count, dtype: int64

### `s.unique()` and `s.nunique()`

In [13]:
categories = pd.Series(['Electronics', 'Clothing', 'Electronics',
                        'Food', 'Clothing', 'Electronics',
                        'Food', 'Toys'])
categories.unique()

<ArrowStringArray>
['Electronics', 'Clothing', 'Food', 'Toys']
Length: 4, dtype: str

In [14]:
categories.nunique()

4

### `s.any()` and `s.all()`

In [15]:
print((prices > 50).any())
print((prices > 15).all())

True
False

## 4.2 The pandas DataFrame

### `pd.DataFrame()`

In [16]:
city_data = {
    'city': ['Tokyo', 'London', 'Paris', 'Berlin'],
    'population_m': [13.9, 8.9, 2.1, 3.7],
    'is_capital': [True, True, True, True],
}
cities_df = pd.DataFrame(city_data)
cities_df

     city  population_m  is_capital
0   Tokyo          13.9        True
1  London           8.9        True
2   Paris           2.1        True
3  Berlin           3.7        True

In [17]:
pd.DataFrame(city_data, index=['JP', 'UK', 'FR', 'DE'])

      city  population_m  is_capital
JP   Tokyo          13.9        True
UK  London           8.9        True
FR   Paris           2.1        True
DE  Berlin           3.7        True

### From a list of dictionaries

In [18]:
employee_records = [
    {'name': 'Alice', 'dept': 'Sales', 'salary': 50000},
    {'name': 'Bob', 'dept': 'IT', 'salary': 60000, 'bonus': 5000},
    {'name': 'Chen', 'dept': 'Sales'},
    {'name': 'Diana', 'dept': 'IT', 'salary': 65000},
]
employees = pd.DataFrame(employee_records)
employees

    name   dept   salary   bonus
0  Alice  Sales  50000.0     NaN
1    Bob     IT  60000.0  5000.0
2   Chen  Sales      NaN     NaN
3  Diana     IT  65000.0     NaN

### From a NumPy array

In [19]:
units = np.array([[120, 135, 150],
                  [ 80,  95,  90],
                  [200, 210, 230]])
regional_units = pd.DataFrame(
    units,
    index=['North', 'Central', 'South'],
    columns=['Jan', 'Feb', 'Mar'],
)
regional_units

         Jan  Feb  Mar
North    120  135  150
Central   80   95   90
South    200  210  230

### A DataFrame with dates as the index

In [20]:
dates = pd.date_range('2025-03-01', periods=6)
readings = pd.DataFrame(
    {
        'temp_c': [31.2, 29.8, 33.5, 30.1, 27.4, 32.0],
        'humidity': [70, 85, 62, 78, 91, 66],
        'rain_mm': [0.0, 12.5, 0.0, 3.2, 25.0, 0.0],
        'sky': ['Sunny', 'Rain', 'Sunny', 'Cloudy', 'Rain', 'Sunny'],
    },
    index=dates,
)
readings

            temp_c  humidity  rain_mm     sky
2025-03-01    31.2        70      0.0   Sunny
2025-03-02    29.8        85     12.5    Rain
2025-03-03    33.5        62      0.0   Sunny
2025-03-04    30.1        78      3.2  Cloudy
2025-03-05    27.4        91     25.0    Rain
2025-03-06    32.0        66      0.0   Sunny

### `df.dtypes`

In [21]:
employees.dtypes

name          str
dept          str
salary    float64
bonus     float64
dtype: object

### `df.shape`

In [22]:
employees.shape

(4, 4)

### `df.columns` and `df.index`

In [23]:
employees.columns

Index(['name', 'dept', 'salary', 'bonus'], dtype='str')

In [24]:
employees.index

RangeIndex(start=0, stop=4, step=1)

## 4.3 Initial Inspection with head(), tail(), sample() and info()

### `df.head()`

In [25]:
customers = pd.DataFrame({
    'customer_id': [1001, 1002, 1003, 1004,
                    1005, 1006, 1007, 1008],
    'name': ['Aisha Rahman', 'Ben Tan', 'Chloe Lim', 'Daniel Wong',
             'Emma Davis', 'Farid Hassan', 'Grace Lee', 'Hari Kumar'],
    'age': [28, 34, 45, 23, 52, 38, 29, 41],
    'city': ['New York', 'Philadelphia', 'Denver', 'Los Angeles',
             'Boston', 'Seattle', 'Austin', 'Philadelphia'],
    'amount': [250.50, 180.75, 420.00, 95.25,
               310.80, 275.40, 150.00, 390.60],
})
customers.head()

   customer_id          name  age          city  amount
0         1001  Aisha Rahman   28      New York  250.50
1         1002       Ben Tan   34  Philadelphia  180.75
2         1003     Chloe Lim   45        Denver  420.00
3         1004   Daniel Wong   23   Los Angeles   95.25
4         1005    Emma Davis   52        Boston  310.80

In [26]:
customers.head(3)

   customer_id          name  age          city  amount
0         1001  Aisha Rahman   28      New York  250.50
1         1002       Ben Tan   34  Philadelphia  180.75
2         1003     Chloe Lim   45        Denver  420.00

### `df.tail()`

In [27]:
customers.tail(3)

   customer_id          name  age          city  amount
5         1006  Farid Hassan   38       Seattle   275.4
6         1007     Grace Lee   29        Austin   150.0
7         1008    Hari Kumar   41  Philadelphia   390.6

### Finding extremes with `sort_values()`

In [28]:
customers.sort_values('amount', ascending=False).head(3)

   customer_id        name  age          city  amount
2         1003   Chloe Lim   45        Denver   420.0
7         1008  Hari Kumar   41  Philadelphia   390.6
4         1005  Emma Davis   52        Boston   310.8

In [29]:
customers.sort_values('age').head(3)

   customer_id          name  age         city  amount
3         1004   Daniel Wong   23  Los Angeles   95.25
0         1001  Aisha Rahman   28     New York  250.50
6         1007     Grace Lee   29       Austin  150.00

### `df.sample()`

In [30]:
customers.sample(3, random_state=42)

   customer_id          name  age          city  amount
1         1002       Ben Tan   34  Philadelphia  180.75
5         1006  Farid Hassan   38       Seattle  275.40
0         1001  Aisha Rahman   28      New York  250.50

In [31]:
customers.sample(frac=0.25, random_state=42)

   customer_id          name  age          city  amount
1         1002       Ben Tan   34  Philadelphia  180.75
5         1006  Farid Hassan   38       Seattle  275.40

### `df.info()`

In [32]:
products = pd.DataFrame({
    'product_id': [101, 102, 103, 104, 105],
    'name': ['Desk Lamp', 'Office Chair', 'Monitor Arm',
             None, 'Keyboard'],
    'category': ['Electronics', 'Furniture', 'Electronics',
                 'Furniture', 'Electronics'],
    'price': [29.99, 149.50, 79.99, 199.99, 39.99],
    'stock': [50, 0, 25, 10, None],
    'rating': [4.5, 4.8, 4.2, 4.9, 4.6],
    'released': pd.to_datetime(['2025-01-15', '2025-03-20',
                                '2025-05-10', '2025-07-08',
                                '2025-09-12']),
})
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   product_id  5 non-null      int64
 1   name        4 non-null      str
 2   category    5 non-null      str
 3   price       5 non-null      float64
 4   stock       4 non-null      float64
 5   rating      5 non-null      float64
 6   released    5 non-null      datetime64[us]
dtypes: datetime64[us](1), float64(3), int64(1), str(2)
memory usage: 504.0 bytes

### Common data types

### Counting missing values

In [33]:
products.isna().sum()

product_id    0
name          1
category      0
price         0
stock         1
rating        0
released      0
dtype: int64

### Spotting numbers stored as text

In [34]:
orders_raw = pd.DataFrame({
    'order_id': ['1001', '1002', '1003', '1004'],
    'amount': ['250.50', '180', 'invalid', '420.00'],
    'quantity': ['5', '3', '7', '2'],
    'order_date': ['2025-01-15', '2025-02-20',
                   '2025-03-10', '2025-04-05'],
})
orders_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    4 non-null      str
 1   amount      4 non-null      str
 2   quantity    4 non-null      str
 3   order_date  4 non-null      str
dtypes: str(4)
memory usage: 342.0 bytes

### An inspection routine

In [35]:
rng = np.random.default_rng(42)
sales = pd.DataFrame({
    'date': pd.date_range('2025-01-01', periods=100),
    'product': rng.choice(['A', 'B', 'C'], 100),
    'units': rng.integers(50, 500, 100),
    'region': rng.choice(['North', 'South', 'East', 'West'], 100),
})
sales.loc[5:7, 'units'] = np.nan


def inspect_df(df):
    print(f'Shape: {df.shape[0]} rows x {df.shape[1]} columns')
    print('\nFirst 3 rows:')
    print(df.head(3))
    print('\nRandom sample:')
    print(df.sample(3, random_state=42))
    print('\nStructure:')
    df.info()
    print('\nMissing values:')
    print(df.isna().sum())


inspect_df(sales)

Shape: 100 rows x 4 columns

First 3 rows:
        date product  units region
0 2025-01-01       A  424.0  South
1 2025-01-02       C  139.0   West
2 2025-01-03       B  412.0  South

Random sample:
         date product  units region
83 2025-03-25       C  363.0  South
53 2025-02-23       B  182.0  South
70 2025-03-12       C   97.0  South

Structure:
<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     100 non-null    datetime64[us]
 1   product  100 non-null    str
 2   units    97 non-null     float64
 3   region   100 non-null    str
dtypes: datetime64[us](1), float64(1), str(2)
memory usage: 3.8 KB

Missing values:
date       0
product    0
units      3
region     0
dtype: int64

## 4.4 The Index

### Default and custom indexes

In [36]:
temps_default.index

RangeIndex(start=0, stop=4, step=1)

In [37]:
temps.index

Index(['New York', 'Philadelphia', 'Denver', 'Los Angeles'], dtype='str')

### Index labels can't be changed in place

In [38]:
product_prices = pd.Series([29.99, 45.50, 19.99],
                           index=['P-100', 'P-200', 'P-300'])
print(len(product_prices.index))
print(product_prices.index[0])
print(product_prices.index[:2].tolist())

3
P-100
['P-100', 'P-200']

The next cell raises an error on purpose.

In [39]:
product_prices.index[0] = 'P-400'

TypeError: Index does not support mutable operations

### Checking whether a label exists

In [40]:
print('P-100' in product_prices.index)
print('P-999' in product_prices.index)

True
False

### `idx.intersection()`, `idx.union()` and `idx.difference()`

In [41]:
store_a = pd.Series([100, 150, 200],
                    index=['Widget_A', 'Widget_B', 'Widget_C'])
store_b = pd.Series([120, 180, 250],
                    index=['Widget_B', 'Widget_C', 'Widget_D'])

In [42]:
store_a.index.intersection(store_b.index)

Index(['Widget_B', 'Widget_C'], dtype='str')

In [43]:
store_a.index.union(store_b.index)

Index(['Widget_A', 'Widget_B', 'Widget_C', 'Widget_D'], dtype='str')

In [44]:
store_a.index.difference(store_b.index)

Index(['Widget_A'], dtype='str')

### Duplicate labels and `is_unique`

In [45]:
codes = pd.Series([10, 20, 30, 40], index=['A', 'B', 'A', 'C'])
codes.index.is_unique

False

In [46]:
codes['B']

np.int64(20)

In [47]:
codes['A']

A    10
A    30
dtype: int64

### How the index lines up data

In [48]:
jan_sales = pd.Series([50000, 45000, 60000],
                      index=['Store_A', 'Store_B', 'Store_C'])
feb_sales = pd.Series([62000, 52000, 47000],
                      index=['Store_C', 'Store_A', 'Store_B'])
jan_sales + feb_sales

Store_A    102000
Store_B     92000
Store_C    122000
dtype: int64

In [49]:
feb_sales_new = pd.Series(
    [52000, 47000, 62000, 30000],
    index=['Store_A', 'Store_B', 'Store_C', 'Store_D'],
)
jan_sales + feb_sales_new

Store_A    102000.0
Store_B     92000.0
Store_C    122000.0
Store_D         NaN
dtype: float64

## 4.5 Selecting Columns

### `df['column']`

In [50]:
readings['temp_c']

2025-03-01    31.2
2025-03-02    29.8
2025-03-03    33.5
2025-03-04    30.1
2025-03-05    27.4
2025-03-06    32.0
Freq: D, Name: temp_c, dtype: float64

### `df[['col1', 'col2']]`

In [51]:
readings[['sky', 'temp_c']]

               sky  temp_c
2025-03-01   Sunny    31.2
2025-03-02    Rain    29.8
2025-03-03   Sunny    33.5
2025-03-04  Cloudy    30.1
2025-03-05    Rain    27.4
2025-03-06   Sunny    32.0

The next cell raises an error on purpose.

In [52]:
readings['sky', 'temp_c']

KeyError: ('sky', 'temp_c')

In [53]:
readings[['humidity']].head(2)

            humidity
2025-03-01        70
2025-03-02        85

### `df.column`

In [54]:
readings.humidity.head(2)

2025-03-01    70
2025-03-02    85
Freq: D, Name: humidity, dtype: int64

In [55]:
survey = pd.DataFrame({
    'Product Name': ['Widget A', 'Widget B'],
    'Units Sold': [150, 120],
    'Revenue ($)': [15000, 12000],
})
survey['Units Sold']

0    150
1    120
Name: Units Sold, dtype: int64

In [56]:
stats = pd.DataFrame({'count': [5, 10, 15], 'sum': [500, 1000, 1500]})
stats.count

<bound method DataFrame.count of    count   sum
0      5   500
1     10  1000
2     15  1500>

In [57]:
stats['count']

0     5
1    10
2    15
Name: count, dtype: int64

### `df.to_numpy()`

In [58]:
measurements = pd.DataFrame({
    'x1': [1.2, 2.3, 3.1],
    'x2': [4.5, 5.2, 6.8],
    'x3': [7.1, 8.9, 9.3],
})
measurements.to_numpy()

array([[1.2, 4.5, 7.1],
       [2.3, 5.2, 8.9],
       [3.1, 6.8, 9.3]])

In [59]:
staff = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Chen'],
    'age': [25, 30, 35],
    'salary': [50000.0, 60000.0, 75000.0],
})
staff.to_numpy()

array([['Alice', 25, 50000.0],
       ['Bob', 30, 60000.0],
       ['Chen', 35, 75000.0]], dtype=object)

## 4.6 Selecting Rows and Cells with .loc and .iloc

In [60]:
readings

            temp_c  humidity  rain_mm     sky
2025-03-01    31.2        70      0.0   Sunny
2025-03-02    29.8        85     12.5    Rain
2025-03-03    33.5        62      0.0   Sunny
2025-03-04    30.1        78      3.2  Cloudy
2025-03-05    27.4        91     25.0    Rain
2025-03-06    32.0        66      0.0   Sunny

### `df.loc[]`

In [61]:
readings.loc['2025-03-02']

temp_c      29.8
humidity      85
rain_mm     12.5
sky         Rain
Name: 2025-03-02 00:00:00, dtype: object

In [62]:
readings.loc['2025-03-02':'2025-03-04']

            temp_c  humidity  rain_mm     sky
2025-03-02    29.8        85     12.5    Rain
2025-03-03    33.5        62      0.0   Sunny
2025-03-04    30.1        78      3.2  Cloudy

In [63]:
readings.loc[['2025-03-02', '2025-03-04'], ['temp_c', 'sky']]

            temp_c     sky
2025-03-02    29.8    Rain
2025-03-04    30.1  Cloudy

In [64]:
readings.loc['2025-03-02':'2025-03-04', 'temp_c':'rain_mm']

            temp_c  humidity  rain_mm
2025-03-02    29.8        85     12.5
2025-03-03    33.5        62      0.0
2025-03-04    30.1        78      3.2

### `df.iloc[]`

In [65]:
readings.iloc[2]

temp_c       33.5
humidity       62
rain_mm       0.0
sky         Sunny
Name: 2025-03-03 00:00:00, dtype: object

In [66]:
readings.iloc[1:4]

            temp_c  humidity  rain_mm     sky
2025-03-02    29.8        85     12.5    Rain
2025-03-03    33.5        62      0.0   Sunny
2025-03-04    30.1        78      3.2  Cloudy

In [67]:
readings.iloc[[0, 2, 4], [0, 3]]

            temp_c    sky
2025-03-01    31.2  Sunny
2025-03-03    33.5  Sunny
2025-03-05    27.4   Rain

In [68]:
readings.iloc[1:4, 0:2]

            temp_c  humidity
2025-03-02    29.8        85
2025-03-03    33.5        62
2025-03-04    30.1        78

The next cell raises an error on purpose.

In [69]:
readings.iloc['2025-03-02']

TypeError: Cannot index by location index with a non-integer key

### `df.at[]` and `df.iat[]`

In [70]:
print(readings.at['2025-03-03', 'humidity'])
print(readings.iat[2, 1])

62
62

### Filtering rows with a condition

In [71]:
readings['rain_mm'] > 0

2025-03-01    False
2025-03-02     True
2025-03-03    False
2025-03-04     True
2025-03-05     True
2025-03-06    False
Freq: D, Name: rain_mm, dtype: bool

In [72]:
readings[readings['rain_mm'] > 0]

            temp_c  humidity  rain_mm     sky
2025-03-02    29.8        85     12.5    Rain
2025-03-04    30.1        78      3.2  Cloudy
2025-03-05    27.4        91     25.0    Rain

In [73]:
readings.loc[readings['rain_mm'] > 0, ['rain_mm', 'sky']]

            rain_mm     sky
2025-03-02     12.5    Rain
2025-03-04      3.2  Cloudy
2025-03-05     25.0    Rain

### Combining conditions

In [74]:
readings[(readings['temp_c'] > 30) & (readings['rain_mm'] == 0)]

            temp_c  humidity  rain_mm    sky
2025-03-01    31.2        70      0.0  Sunny
2025-03-03    33.5        62      0.0  Sunny
2025-03-06    32.0        66      0.0  Sunny

### `s.isin()`

In [75]:
readings[readings['sky'].isin(['Rain', 'Cloudy'])]

            temp_c  humidity  rain_mm     sky
2025-03-02    29.8        85     12.5    Rain
2025-03-04    30.1        78      3.2  Cloudy
2025-03-05    27.4        91     25.0    Rain

### Changing values with `.loc`

In [76]:
readings.loc['2025-03-04', 'rain_mm'] = 4.0
readings.loc['2025-03-04']

temp_c        30.1
humidity        78
rain_mm        4.0
sky         Cloudy
Name: 2025-03-04 00:00:00, dtype: object

In [77]:
readings.loc[readings['rain_mm'] > 10, 'sky'] = 'Rain'
readings['sky'].value_counts()

sky
Sunny     3
Rain      2
Cloudy    1
Name: count, dtype: int64

## 4.7 Setting and Resetting the Index

In [78]:
countries = pd.DataFrame({
    'country': ['USA', 'China', 'India', 'Brazil', 'Germany'],
    'continent': ['North America', 'Asia', 'Asia',
                  'South America', 'Europe'],
    'population_m': [331, 1444, 1393, 213, 83],
    'gdp_trillion': [21.4, 14.7, 2.9, 1.8, 3.8],
})
countries

   country      continent  population_m  gdp_trillion
0      USA  North America           331          21.4
1    China           Asia          1444          14.7
2    India           Asia          1393           2.9
3   Brazil  South America           213           1.8
4  Germany         Europe            83           3.8

### `df.set_index()`

In [79]:
countries_by_name = countries.set_index('country')
countries_by_name

             continent  population_m  gdp_trillion
country
USA      North America           331          21.4
China             Asia          1444          14.7
India             Asia          1393           2.9
Brazil   South America           213           1.8
Germany         Europe            83           3.8

In [80]:
countries_by_name.loc['China']

continent       Asia
population_m    1444
gdp_trillion    14.7
Name: China, dtype: object

In [81]:
countries.set_index('country', drop=False).head(2)

        country      continent  population_m  gdp_trillion
country
USA         USA  North America           331          21.4
China     China           Asia          1444          14.7

In [82]:
countries_multi = countries.set_index(['continent', 'country'])
countries_multi

                       population_m  gdp_trillion
continent     country
North America USA               331          21.4
Asia          China            1444          14.7
              India            1393           2.9
South America Brazil            213           1.8
Europe        Germany            83           3.8

In [83]:
countries_multi.loc['Asia']

         population_m  gdp_trillion
country
China            1444          14.7
India            1393           2.9

### `df.reset_index()`

In [84]:
countries_by_name.reset_index()

   country      continent  population_m  gdp_trillion
0      USA  North America           331          21.4
1    China           Asia          1444          14.7
2    India           Asia          1393           2.9
3   Brazil  South America           213           1.8
4  Germany         Europe            83           3.8

In [85]:
countries_by_name.reset_index(drop=True).head(2)

       continent  population_m  gdp_trillion
0  North America           331          21.4
1           Asia          1444          14.7

### Resetting after a filter

In [86]:
asia = countries[countries['continent'] == 'Asia']
asia

  country continent  population_m  gdp_trillion
1   China      Asia          1444          14.7
2   India      Asia          1393           2.9

In [87]:
asia = asia.reset_index(drop=True)
asia

  country continent  population_m  gdp_trillion
0   China      Asia          1444          14.7
1   India      Asia          1393           2.9

### Putting it together

In [88]:
orders = pd.DataFrame({
    'order_id': ['ORD001', 'ORD002', 'ORD003', 'ORD004', 'ORD005'],
    'customer': ['Alice', 'Bob', 'Alice', 'Chen', 'Bob'],
    'amount': [250, 450, 120, 890, 340],
    'status': ['Shipped', 'Pending', 'Shipped', 'Shipped',
               'Cancelled'],
})
orders = orders.set_index('order_id')
print('ORD003 amount:', orders.loc['ORD003', 'amount'])

shipped = orders[orders['status'] == 'Shipped'].reset_index()
shipped

ORD003 amount: 120

  order_id customer  amount   status
0   ORD001    Alice     250  Shipped
1   ORD003    Alice     120  Shipped
2   ORD004     Chen     890  Shipped

In [89]:
orders['customer'].is_unique

False