# Chapter 2: Core Python Concepts: Variables, Types, and Control Flow

Companion notebook for *Master Data Cleaning: A Hands-On Beginner's Guide with Python, pandas & NumPy*.

Run the cells from top to bottom (**Kernel → Restart Kernel and Run All Cells**). The data files this chapter uses are in the same folder as this notebook.

## 2.1 Variables and Scalar Types

In [1]:
import pandas as pd

### Variables and assignment

In [2]:
quantity = 10
product = "Widget A"
unit_price = 19.99
print(quantity, product, unit_price)

10 Widget A 19.99

### Integers and floats

In [3]:
a, b = 10, 3
print(a + b, a - b, a * b)
print(a / b)
print(a // b, a % b, a ** b)

13 7 30
3.3333333333333335
3 1 1000

In [4]:
42 // 10

4

### Floating-point precision

In [5]:
total = 0.1 + 0.2
print(total)
print(total == 0.3)

0.30000000000000004
False

### Strings

In [6]:
note = "It's out of stock"
quote = 'She said "Hello"'
print(note)
print(quote)

It's out of stock
She said "Hello"

In [7]:
first, last = "Aisha", "Rahman"
full_name = first + " " + last
print(full_name, len(full_name))
print("-" * 12)

Aisha Rahman 12
------------

#### Indexing and slicing

In [8]:
code = "US-NY-2024"
print(code[0], code[-1])
print(code[0:2])
print(code[6:])

U 4
US
2024

#### String methods

In [9]:
raw = "  Data Cleaning  "
print(repr(raw.strip()))
print(repr(raw.lower()))
print(repr(raw.upper()))
print(repr(raw.replace("Cleaning", "Analysis")))
print(raw.strip().startswith("Data"))

'Data Cleaning'
'  data cleaning  '
'  DATA CLEANING  '
'  Data Analysis  '
True

In [10]:
raw = raw.strip()
raw

'Data Cleaning'

#### f-strings

In [11]:
name, total = "Aisha", 1234.5
print(f"{name} spent ${total:.2f}")

Aisha spent $1234.50

### Booleans

In [12]:
age = 25
print(age > 18, age == 25, age != 30)

True True True

In [13]:
has_id = True
has_ticket = False
print(age >= 18 and has_id)
print(has_id or has_ticket)
print(not has_ticket)

True
True
True

### Checking and converting types

In [14]:
print(type(42), type(19.99))
print(type("42"), type(True))

<class 'int'> <class 'float'>
<class 'str'> <class 'bool'>

In [15]:
print(int("42") + 1)
print(float("3.14"))
print(int(9.99))
print(str(25) + " units")

43
3.14
9
25 units

In [16]:
print(bool(0), bool(""), bool(None))
print(bool(1), bool("No"))

False False False
True True

The next cell raises an error on purpose.

In [17]:
int("12 units")

ValueError: invalid literal for int() with base 10: '12 units'

### Useful built-in functions

In [18]:
prices = [19.99, 24.50, 15.75, 32.00]
print(len(prices), min(prices), max(prices))
print(round(sum(prices), 2))
print(round(sum(prices) / len(prices), 2))
print(abs(-42))

4 15.75 32.0
92.24
23.06
42

## 2.2 Lists

In [19]:
cities = ["New York", "London", "Tokyo", "Paris"]
mixed = [42, "Aisha", 3.14, True, None]
print(cities)
print(mixed)

['New York', 'London', 'Tokyo', 'Paris']
[42, 'Aisha', 3.14, True, None]

In [20]:
list(range(1, 6))

[1, 2, 3, 4, 5]

### Indexing and slicing

In [21]:
products = ["Widget A", "Widget B", "Widget C", "Widget D"]
print(products[0], "|", products[-1])

Widget A | Widget D

In [22]:
data = [10, 20, 30, 40, 50, 60, 70, 80]
print(data[1:4])
print(data[:3])
print(data[-3:])
print(data[::2])
print(data[::-1])

[20, 30, 40]
[10, 20, 30]
[60, 70, 80]
[10, 30, 50, 70]
[80, 70, 60, 50, 40, 30, 20, 10]

In [23]:
prices = [10.99, 15.50, 8.25, 22.00]
prices[2] = 9.99
prices[-1] = 19.99
prices

[10.99, 15.5, 9.99, 19.99]

### Combining lists and checking membership

In [24]:
print([1, 2, 3] + [4, 5])
print([0] * 5)

[1, 2, 3, 4, 5]
[0, 0, 0, 0, 0]

In [25]:
valid_categories = ["Electronics", "Clothing", "Food", "Books"]
print("Food" in valid_categories)
print("Toys" in valid_categories)
print("Toys" not in valid_categories)

True
False
True

### Copies versus references

In [26]:
original = [1, 2, 3]
alias = original
alias.append(4)
print(original)
print(alias is original)

[1, 2, 3, 4]
True

In [27]:
original = [1, 2, 3]
backup = original.copy()
backup.append(4)
print(original)
print(backup)

[1, 2, 3]
[1, 2, 3, 4]

### List methods

In [28]:
items = [1, 2, 3]
items.append([4, 5])
print(items)

items = [1, 2, 3]
items.extend([4, 5])
print(items)

[1, 2, 3, [4, 5]]
[1, 2, 3, 4, 5]

In [29]:
readings = [10, 20, 30, 20, 40]
readings.remove(20)
print(readings)
last = readings.pop()
print(last, readings)

[10, 30, 20, 40]
40 [10, 30, 20]

In [30]:
statuses = ["paid", "pending", "paid", "refunded", "paid"]
print(statuses.count("paid"))
print(statuses.index("refunded"))

3
3

#### `list.sort()` and `sorted()`

In [31]:
scores = [45, 12, 89, 3, 67]
print(sorted(scores))
print(scores)
scores.sort(reverse=True)
print(scores)

[3, 12, 45, 67, 89]
[45, 12, 89, 3, 67]
[89, 67, 45, 12, 3]

## 2.3 Tuples and Unpacking

### Creating tuples

In [32]:
point = (3, 4)
record = ("Aisha", 30, "Engineer")
single = (42,)
not_a_tuple = (42)
print(point, record, single)
print(type(single), type(not_a_tuple))

(3, 4) ('Aisha', 30, 'Engineer') (42,)
<class 'tuple'> <class 'int'>

The next cell raises an error on purpose.

In [33]:
point[0] = 10

TypeError: 'tuple' object does not support item assignment

### Unpacking

In [34]:
name, age, job = record
print(name)
print(job)

Aisha
Engineer

In [35]:
low, high = 90, 10
low, high = high, low
print(low, high)

10 90

In [36]:
name, _, job = record
print(name, job)

first, *rest = [5, 8, 2, 9]
print(first, rest)

Aisha Engineer
5 [8, 2, 9]

### Returning several values from a function

In [37]:
def price_range(prices):
    return min(prices), max(prices)

cheapest, dearest = price_range([19.99, 24.50, 15.75, 32.00])
print(cheapest, dearest)

15.75 32.0

### Unpacking in loops with `enumerate()` and `zip()`

In [38]:
products = ["Widget A", "Widget B", "Widget C"]
prices = [10.99, 15.50, 8.25]
quantities = [100, 50, 200]

for position, product in enumerate(products):
    print(position, product)

for product, price, qty in zip(products, prices, quantities):
    print(f"{product}: {qty} x {price:.2f} = {price * qty:.2f}")

0 Widget A
1 Widget B
2 Widget C
Widget A: 100 x 10.99 = 1099.00
Widget B: 50 x 15.50 = 775.00
Widget C: 200 x 8.25 = 1650.00

## 2.4 Dictionaries

### Creating and reading dictionaries

In [39]:
customer = {"name": "Aisha Rahman", "age": 30, "city": "Philadelphia"}
customer["name"]

'Aisha Rahman'

In [40]:
fields = ["name", "age", "city"]
values = ["Ben Tan", 35, "Denver"]
dict(zip(fields, values))

{'name': 'Ben Tan', 'age': 35, 'city': 'Denver'}

The next cell raises an error on purpose.

In [41]:
customer["email"]

KeyError: 'email'

### `dict.get()`

In [42]:
print(customer.get("email"))
print(customer.get("email", "unknown"))
print(customer.get("city", "unknown"))

None
unknown
Philadelphia

In [43]:
print("age" in customer)
print("Philadelphia" in customer)

True
False

### Adding, changing and removing entries

In [44]:
customer["age"] = 31
customer["email"] = "aisha@mail.com"
del customer["city"]
customer

{'name': 'Aisha Rahman', 'age': 31, 'email': 'aisha@mail.com'}

In [45]:
customer.update({"age": 32, "tier": "Gold"})
customer

{'name': 'Aisha Rahman', 'age': 32, 'email': 'aisha@mail.com', 'tier': 'Gold'}

### `dict.keys()`, `dict.values()` and `dict.items()`

In [46]:
stock = {"Widget A": 120, "Widget B": 0, "Widget C": 45}
print(list(stock.keys()))
print(sum(stock.values()))
for product, units in stock.items():
    print(f"{product}: {units}")

['Widget A', 'Widget B', 'Widget C']
165
Widget A: 120
Widget B: 0
Widget C: 45

### Mapping values with a dictionary

In [47]:
answer_map = {"Yes": True, "Y": True, "No": False, "N": False}
answers = ["Yes", "N", "Y", "No"]
[answer_map[a] for a in answers]

[True, False, True, False]

### Nested dictionaries

In [48]:
company = {
    "name": "Tech Corp",
    "departments": {
        "engineering": {"headcount": 50},
        "sales": {"headcount": 30},
    },
}
company["departments"]["sales"]["headcount"]

30

### From dictionary to DataFrame

In [49]:
inventory = pd.DataFrame({
    "product": ["Widget A", "Widget B", "Widget C"],
    "price": [19.99, 24.50, 15.75],
    "stock": [100, 50, 200],
})
inventory

    product  price  stock
0  Widget A  19.99    100
1  Widget B  24.50     50
2  Widget C  15.75    200

## 2.5 Conditional Logic with `if`, `elif` and `else`

### The `if` statement

In [50]:
age = 25

if age >= 18:
    print("Adult")
    print("Access granted")

print("This line always runs")

Adult
Access granted
This line always runs

In [51]:
order_total = 850

if order_total >= 1000:
    size = "Large"
elif order_total >= 500:
    size = "Medium"
elif order_total > 0:
    size = "Small"
else:
    size = "Invalid"

size

'Medium'

### Combining conditions

In [52]:
age = 25
email = "user@example.com"

age_ok = 0 <= age <= 120
email_ok = "@" in email and "." in email

if age_ok and email_ok:
    print("Record valid")
else:
    print("Record needs review")

Record valid

In [53]:
payment = "paypal"

if payment == "cash" or payment == "card":
    print("Pay at counter")
else:
    print("Pay online")

Pay online

In [54]:
age, income, credit_score = 25, 45000, 650

if (21 <= age <= 65) and (income >= 30000 or credit_score >= 700):
    print("Approved")

Approved

### Truthiness

In [55]:
comment = ""

if not comment:
    print("No comment provided")

No comment provided

In [56]:
quantity = 0

if quantity:
    print("Has quantity")
else:
    print("Treated as missing")

if quantity is not None:
    print(f"Quantity recorded: {quantity}")

Treated as missing
Quantity recorded: 0

### Conditional expressions

In [57]:
quantity = 150
unit_price = 8.50 if quantity >= 100 else 10.00

username = ""
display_name = username if username else "Guest"
print(unit_price, display_name)

8.5 Guest

## 2.6 Loops and Comprehensions

### The `for` loop

In [58]:
for fruit in ["apple", "banana", "cherry"]:
    print(fruit.upper())

APPLE
BANANA
CHERRY

In [59]:
order_values = [120.0, 75.5, 310.0]
total = 0
for value in order_values:
    total += value
total

505.5

In [60]:
for i in range(3):
    print("Attempt", i + 1)

Attempt 1
Attempt 2
Attempt 3

### Skipping and stopping with `continue` and `break`

In [61]:
raw_emails = ["Aisha@Example.com ", "invalid", "", " ben@example.com"]
emails = []

for email in raw_emails:
    email = email.strip()
    if not email or "@" not in email:
        continue
    emails.append(email.lower())

emails

['aisha@example.com', 'ben@example.com']

In [62]:
required = ["name", "email", "age", "address"]
record = {"name": "Aisha", "email": "aisha@example.com", "age": 30}

missing = None
for field in required:
    if field not in record:
        missing = field
        break

print(f"First missing field: {missing}")

First missing field: address

### Nested loops

In [63]:
for region in ["North", "South"]:
    for status in ["Active", "Closed"]:
        print(region, status)

North Active
North Closed
South Active
South Closed

### List comprehensions

In [64]:
numbers = [1, 2, 3, 4, 5]
[n ** 2 for n in numbers]

[1, 4, 9, 16, 25]

In [65]:
raw_names = ["  aisha ", "BEN", "", "Chen Wei  "]
[name.strip().title() for name in raw_names if name.strip()]

['Aisha', 'Ben', 'Chen Wei']

In [66]:
prices = {"apple": 1.50, "banana": 0.80, "mango": 4.20}
{item: round(p * 0.9, 2) for item, p in prices.items() if p > 1}

{'apple': 1.35, 'mango': 3.78}

## 2.7 Functions and Lambda

### Defining a function with `def`

In [67]:
def add_tax(price, rate):
    return price * (1 + rate)

add_tax(100, 0.06)

106.0

### Default values

In [68]:
def add_tax(price, rate=0.06):
    return round(price * (1 + rate), 2)

print(add_tax(100))
print(add_tax(100, rate=0.1))

106.0
110.0

### Functions that work on DataFrames

In [69]:
def price_summary(table):
    prices = table["price"]
    return prices.sum(), prices.mean(), prices.max()

total, average, highest = price_summary(inventory)
print(f"Total {total:.2f}, average {average:.2f}, max {highest}")

Total 60.24, average 20.08, max 24.5

In [70]:
customers = pd.DataFrame({
    "name": ["  Aisha Rahman", "BEN TAN", "chen wei  "],
    "email": ["AISHA@MAIL.COM", " ben@mail.com", "Chen@Mail.com "],
})
customers

             name           email
0    Aisha Rahman  AISHA@MAIL.COM
1         BEN TAN    ben@mail.com
2      chen wei    Chen@Mail.com

In [71]:
def clean_text_columns(table, columns):
    cleaned = table.copy()
    for column in columns:
        cleaned[column] = cleaned[column].str.strip().str.lower()
    return cleaned

customers_clean = clean_text_columns(customers, ["name", "email"])
customers_clean

           name           email
0  aisha rahman  aisha@mail.com
1       ben tan    ben@mail.com
2      chen wei   chen@mail.com

### Anonymous functions with `lambda`

In [72]:
sales = pd.DataFrame({
    "employee": ["Aisha", "Ben", "Aisha", "Ben", "Aisha"],
    "amount": [100, 150, 200, 120, 180],
})
sales

  employee  amount
0    Aisha     100
1      Ben     150
2    Aisha     200
3      Ben     120
4    Aisha     180

In [73]:
sales["size"] = sales["amount"].apply(
    lambda x: "Large" if x >= 150 else "Small"
)
sales

  employee  amount   size
0    Aisha     100  Small
1      Ben     150  Large
2    Aisha     200  Large
3      Ben     120  Small
4    Aisha     180  Large

In [74]:
sales.groupby("employee")["amount"].agg(lambda x: x.max() - x.min())

employee
Aisha    100
Ben       30
Name: amount, dtype: int64

### Building your own cleaning toolkit

In [75]:
def standardize_phone(phone):
    digits = "".join([ch for ch in phone if ch.isdigit()])
    if len(digits) == 11 and digits.startswith("1"):
        digits = digits[1:]
    return digits

raw_phones = ["+1 212-555-0147", "(212) 555-0147", "312.555.0199"]
[standardize_phone(p) for p in raw_phones]

['2125550147', '2125550147', '3125550199']